// @flow

export const ignore = [
  'Viki Bell',
  'India Jackson',
  'Sarah Jackson',
  'Matt Wollner',
  'David Jackson',
  'Lewis Judd',
  'Rob Wollner',
  'shellpits',
  'suffolk',
  'Richard Fraser',
  'tufnellpark',
  'Tom Bell',
  'India Postcard',
  'John Morrison',
  'James Roblin',
  'Pool',
  'Paul Edwards',
  'Grant Fennell',
  'Rupert Edwards',
  'Camilla Edwards',
  'Jason Guest',
  'Alec Pell-Johnson',
  'Steve Bell',
  'Gill Bell',
  'Ronan McKinless',
  'Angela Edwards',
  'Sarah Ritchie',
  'Dilys Morrison',
  'Ellie Lowe',
  'Henry Pell-Johnson',
  'Rob Armstrong',
  'Paula Pell-Johnson',
  'Matt Bell',
  'Daniel Fogg',
  'dancing',
  'fancydress',
  'Millie Jackson',
  'Nick Roblin',
  'Victoria Edwards',
  'Rosie Lampard',
  'Stef Hunter',
  'Robbie Carver',
  'Hattie Jackson',
  'Terry Bell',
  'Adam Bloomfield',
  'Will Nice',
  'Polly Jackson',
  'Jan Bell',
  'Pete Warwick-Brown',
  'Jamie Robinson',
  'hackerston',
  'Becki Hare',
  'Annie Jackson',
  'Ben Jackson',
  'Ray Berry',
  'Chris McRobbie',
  'graftt',
  'Spike Jackson',
  'Sandy Smith',
  'Caz',
  'camden',
  'Neil Waring',
  'Alex Roblin',
  'Charlotte Simpson',
  'TheDolphin',
  'Jane Roblin',
  'Tom OHara',
  'Liam Brennan',
  'Maddie',
  'show',
  'leighonsea',
  'Dan Attfield',
  'Matt Watson',
  'Matt Meakin',
  'Chris Bell',
  'Sophie Gaze',
  'George Allen',
  'Laura Jackson',
  'Anna Carver',
  'Alice Plein',
  'glemhamhall',
  'datenight',
  'Hugh Smith',
  'Vicky Hill',
  'Paul Roblin',
  'london',
  'Rachel Farrant',
  'SuperCouth',
  'Ket',
  'Calendar',
  'Luke Evans',
];

export default {
  drinkies: 'glass-cheers',
  champagne: 'glass-cheers',
  Work: 'laptop',
  food: 'utensils',
  improv: 'laugh-squint',
  wedding: 'heart',
  pizza: 'utensils',
  gaming: 'gamepad',
  christmas: 'candy-cane',
  Wine: 'wine-glass-alt',
  wine: 'wine-glass-alt',
  Pub: 'beer',
  beer: 'beer',
  holiday: 'plane-departure',
  Games: 'gamepad',
  boardgames: 'gamepad',
  party: 'glass-cheers',
  Dinner: 'utensils',
  'Take Away': 'utensils',
  dinner: 'utensils',
  bath: 'bath',
  birthday: 'birthday-cake',
  hangover: 'sad-tear',
  gig: 'music',
  music: 'music',
  'Llama Narla Bell Jackson': 'dog',
  beach: 'umbrella-beach',
  festival: 'campground',
  diy: 'tools',
  bbq: 'utensils',
  Programming: 'laptop',
  'Dungeon And Dragons': 'khanda',
  themiller: 'laugh-squint',
  roast: 'utensils',
};
